Add setup.py to support installation via setuptools
fuhry/piclicktrack pull request #2
Opened 2017-01-03 05:31 UTC by Conan-Kudo

This `setup.py` should properly install `piclicktrack` onto a system using `pip`/`pip3`, provided the dependencies can be satisfied.

I set the version to `0.0.0` and the state to `2 - Pre-Alpha` because I wasn't sure what you wanted to consider it as. Feel free to let me know what is should be, and I'll change it. Alternatively, you can merge it and change it yourself.

2017-01-03 06:47 UTC, Conan-Kudo commented
I've also created [test Fedora 25 packages](https://software.opensuse.org/download.html?project=home%3APharaoh_Atem%3Apiclicktrack&package=piclicktrack) using this patch. You can try it out and see whether it installed files correctly.

2017-01-04 05:28 UTC, Conan-Kudo commented
@fuhry I've updated based on your newest commits, but I do not have the ability to express `PyQt5 or PyQt4`, I think. So I've left it to be `PyQt5`.

2017-01-04 05:45 UTC, fuhry requested changes
Please indent with tabs for consistency with the rest of the codebase.

2017-01-04 05:52 UTC, Conan-Kudo commented
@fuhry Done.

2017-01-04 05:57 UTC, fuhry approved these changes

2017-01-04 05:57 UTC, merged